springdoc:
    swagger-ui:
        path: /swagger-api.html
    api-docs:
        path: /api-docs

api:
  prefix: /api/v1

jwt:
  expiration: 30 # 30 days
  refreshExpiration: 5184000 #60 days
  secretKey : fXgR+2uSB9d+LmMOn5ryQi973KUQmM1AauOZSiHAULc=

spring:
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/zola_db?authSource=admin
      username: root
      password: 123456
      host: localhost
      port: 27017
      database: zola_db
      authentication-database: admin
