springdoc:
    swagger-ui:
        path: /swagger-api.html
    api-docs:
        path: /api-docs

api:
  prefix: /api/v1

jwt:
  expiration: 30 # 30 days
  refreshExpiration: 5184000 #60 days
  secretKey : fXgR+2uSB9d+LmMOn5ryQi973KUQmM1AauOZSiHAULc=

spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@localhost:${MONGODB_LOCAL_PORT}/zola_db?authSource=admin
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}
      host: ${MONGODB_HOST}
      port: ${MONGODB_LOCAL_PORT}
      database: ${MONGODB_DATABASE}
      authentication-database: admin
  messages:
    basename: i18n/messages