name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bezola-app .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bezola-app:latest
      - name: Copy source to code to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ubuntu/bezola-app"

  deploy:
    needs: build
    runs-on: [bezola]
    steps:
      - name: Pull Image from docker hub
        run: docker pull phoaian/bezola-app:latest
      - name: Delete old containers
        run: docker rm -f bezola
      - name: Run docker compose
        run: docker-compose -f /home/ubuntu/bezola-app/docker-compose.yml up -d
