name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: './docker-compose.yml'
        env:
          MONGODB_USER: 'root'
          MONGODB_PASSWORD: '123456'
          MONGODB_DATABASE: 'zola_db'
          MONGODB_LOCAL_PORT: '27017'
          MONGODB_DOCKER_PORT: '27017'
          SPRING_LOCAL_PORT: '9090'
          SPRING_DOCKER_PORT: '8080'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bezola-app .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bezola-app:latest

  deploy:
    needs: build
    runs-on: [bezola]
    steps:
      - name: Pull Image from docker hub
        run: docker pull phoaian/bezola-app:latest
      - name: Delete old containers
        run: docker rm -f bezola
      - name: Run docker compose
        run: docker-compose up -d
