name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bezola-app .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bezola-app:latest

  deploy:
    needs: build
    runs-on: [bezola]
    steps:
      - name: Pull Image from docker hub
        run: docker pull phoaian/bezola-app:latest
      - name: Delete old containers
        run: docker rm -f bezola
      - name: Run docker compose
        run: docker-compose -f ./docker-compose.yml up -d
